export const ERROR = {
  GET_ERRORS: "GET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
};

export const LOGIN = {
  LOGIN_BEGIN: "LOGIN_BEGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
};

export const REGISTER = {
  REGISTER_BEGIN: "REGISTER_BEGIN",
  REQISTER_SUCCESS: "REGISTER_SUCCESS",
  REQISTER_FAIL: "REGISTER_FAIL",
};

export const LOGOUT = {
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const GET_SUCCESS_MESSAGE = {
  GET_MESSAGE: "GET_MESSAGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
};

export const PROFILE_DATA = {
  FETCH_BEGIN: "FETCH_BEGIN",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAIL: "FETCH_FAIL",

  UPDATE_PROFILE_DATA_BEGIN: "UPDATE_PROFILE_DATA_BEGIN",
  UPDATE_PROFILE_DATA_SUCCESS: "UPDATE_PROFILE_DATA_SUCCESS",
  UPDATE_PROFILE_DATA_FAIL: "UPDATE_PROFILE_DATA_FAIL",
};

export const QUESTION = {
  UPDATE_QUESTION_DATA_BEGIN: "UPDATE_QUESTION_DATA_BEGIN",
  UPDATE_QUESTION_DATA_SUCCESS: "UPDATE_QUESTION_DATA_SUCCESS",
  UPDATE_QUESTION_DATA_FAIL: "UPDATE_QUESTION_DATA_FAIL",

  FETCH_QUESTION_DATA_BEGIN: "FETCH_QUESTION_DATA_BEGIN",
  FETCH_QUESTION_DATA_SUCCESS: "FETCH_QUESTION_DATA_SUCCESS",
  FETCH_QUESTION_DATA_FAIL: "FETCH_QUESTION_DATA_FAIL",

  DELETE_QUESTION_DATA_BEGIN: "DELETE_QUESTION_DATA_BEGIN",
  DELETE_QUESTION_DATA_SUCCESS: "DELETE_QUESTION_DATA_SUCCESS",
  DELETE_QUESTION_DATA_FAIL: "DELETE_QUESTION_DATA_FAIL",
};

export const ASSESSMENT = {
  CREATE_ASSESSMENT_OBJ_BEGIN: "CREATE_ASSESSMENT_OBJ_BEGIN",
  CREATE_ASSESSMENT_OBJ_SUCCESS: "CREATE_ASSESSMENT_OBJ_SUCCESS",
  CREATE_ASSESSMENT_OBJ_FAIL: "CREATE_ASSESSMENT_OBJ_SUCCESS",

  UPDATE_ASSESSMENT_SETTINGS_BEGIN: "UPDATE_ASSESSMENT_SETTINGS_BEGIN",
  UPDATE_ASSESSMENT_SETTINGS_SUCCESS: "UPDATE_ASSESSMENT_SETTINGS_SUCCESS",
  UPDATE_ASSESSMENT_SETTINGS_FAIL: "UPDATE_ASSESSMENT_SETTINGS_SUCCESS",

  FETCH_ASSESSMENT_SETTINGS_BEGIN: "FETCH_ASSESSMENT_SETTINGS_BEGIN",
  FETCH_ASSESSMENT_SETTINGS_SUCCESS: "FETCH_ASSESSMENT_SETTINGS_SUCCESS",
  FETCH_ASSESSMENT_SETTINGS_FAIL: "FETCH_ASSESSMENT_SETTINGS_FAIL",

  UPDATE_ASSESSMENT_ACCESS_BEGIN: "UPDATE_ASSESSMENT_ACCESS_BEGIN",
  UPDATE_ASSESSMENT_ACCESS_SUCCESS: "UPDATE_ASSESSMENT_ACCESS_SUCCESS",
  UPDATE_ASSESSMENT_ACCESS_FAIL: "UPDATE_ASSESSMENT_ACCESS_FAIL",

  FETCH_ASSESSMENT_ACCESS_BEGIN: "FETCH_ASSESSMENT_ACCESS_BEGIN",
  FETCH_ASSESSMENT_ACCESS_SUCCESS: "FETCH_ASSESSMENT_ACCESS_SUCCESS",
  FETCH_ASSESSMENT_ACCESS_FAIL: "FETCH_ASSESSMENT_ACCESS_FAIL",
};

export const ASSESSMENT_QUESTION = {
  ADD_ASSESSMENT_QUESTION_BEGIN: "ADD_ASSESSMENT_QUESTION_BEGIN",
  ADD_ASSESSMENT_QUESTION_SUCCESS: "ADD_ASSESSMENT_QUESTION_SUCCESS",
  ADD_ASSESSMENT_QUESTION_FAIL: "ADD_ASSESSMENT_QUESTION_FAIL",

  FETCH_ALL_ASSESSMENT_QUESTION_BEGIN: "FETCH_ALL_ASSESSMENT_QUESTION_BEGIN",
  FETCH_ALL_ASSESSMENT_QUESTION_SUCCESS: "FETCH_ALL_ASSESSMENT_QUESTION_SUCCESS",
  FETCH_ALL_ASSESSMENT_QUESTION_FAIL: "FETCH_ALL_ASSESSMENT_QUESTION_FAIL",

  UPDATE_ALL_ASSESSMENT_QUESTION_BEGIN: "UPDATE_ALL_ASSESSMENT_QUESTION_BEGIN",
  UPDATE_ALL_ASSESSMENT_QUESTION_SUCCESS: "UPDATE_ALL_ASSESSMENT_QUESTION_SUCCESS",
  UPDATE_ALL_ASSESSMENT_QUESTION_FAIL: "UPDATE_ALL_ASSESSMENT_QUESTION_FAIL",
};
