export const LOGIN_ACTION = {
  LOGIN_USER_ACCOUNT: "LOGIN_USER_ACCOUNT",

  RESPONSE_LOGIN_USER_ACCOUNT_SUCCESS: "RESPONSE_LOGIN_USER_ACCOUNT_SUCCESS",
  RESPONSE_LOGIN_USER_ACCOUNT_FAIL: "RESPONSE_LOGIN_USER_ACCOUNT_FAIL",
};

export const LOGOUT_ACTION = {
  USER_LOGOUT: "USER_LOGOUT",
};

export const SAMPLE = {
  GET_ERRORS: "GET_ERRORS",
  USER_LOADING: "USER_LOADING",
  SET_CURRENT_USER: "SET_CURRENT_USER",
};
