export const ERROR = {
  GET_ERRORS: "GET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
};

export const LOGIN = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
};

export const REGISTER = {
  REQISTER_SUCCESS: "REGISTER_SUCCESS",
  REQISTER_FAIL: "REGISTER_FAIL",
};

export const LOGOUT = {
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const GET_SUCCESS_MESSAGE = {
  GET_MESSAGE: "GET_MESSAGE",
};

export const FETCH_PROFILE_DATA = {
  FETCH_BEGIN: "FETCH_BEGIN",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAIL: "FETCH_FAIL",
};
